dist: bionic
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
#  - "pypy3" lets not do pypy right now

before_install:
  - pip install poetry
  # Fix issue with Python 3.7 and 3.8 build failure caused by "setuptools"
  #   AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
  - pip install setuptools==60.8.2

install:
  - poetry install

script:
  - poetry run black . --check
  - poetry run mypy runrestic --ignore-missing-imports --strict
  - poetry run pytest
